### ISSUE TITLE
can't get certain doujinshis

### ISSUE THREAD

**Issue by lukeovalle** [groussel42/nhentai-api#1]
With specific IDs, the api raises an exception.

```
irb(main):004:0> Doujinshi.new 290133
Traceback (most recent call last):
        6: from /usr/bin/irb:23:in `<main>'
        5: from /usr/bin/irb:23:in `load'
        4: from /usr/lib64/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):4
        2: from (irb):4:in `new'
        1: from /usr/lib64/ruby/gems/2.6.0/gems/nhentai-api-0.2.0/lib/nhentai-api.rb:22:in `initialize'
NoMethodError (undefined method `[]' for nil:NilClass)
```

**Comment by groussel42** [comment]
Hello @lukeovalle and thanks for the report.
Sorry for the long delay, didn't notice someone created a issue!

The exception was due to a hardcoded string I forgot to change before pushing.
It has been changed in the last commit: https://github.com/groussel42/nhentai-api/commit/215145ca03b3007a20f0c7ecf31013d85f7bfb7b
